### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by gabkov** [Team-Kujira/core#50]
Hi,

I was trying to follow this [tutorial](https://docs.kujira.app/developers/smart-contracts) but the `make install` step fails with the following error and no binaries being generated: 

```console
➜  core git:(master) make install
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=kujira -X github.com/cosmos/cosmos-sdk/version.ServerName=kujirad -X github.com/cosmos/cosmos-sdk/version.Version=0.9.1-1-g5549501 -X github.com/cosmos/cosmos-sdk/version.Commit=554950147825e94fa52c3ff0a3b138568cf7c774 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/kujirad
# github.com/Team-Kujira/core/cmd/kujirad
ld: warning: '/private/var/folders/nh/78bdkps97rv6pdws74j1xy0w0000gn/T/go-link-1563688512/go.o' has malformed LC_DYSYMTAB, expected 133 undefined symbols to start at index 108006, found 251 undefined symbols starting at index 135
```

macOS: 14.2.1
go version: go1.20.6 darwin/arm64

Based on [#61229](https://github.com/golang/go/issues/61229) I suspect it has to do something with the apple linker. Any suggestion appreciated.

**Comment by codehans** [comment]
> Hi,
> 
> I was trying to follow this [tutorial](https://docs.kujira.app/developers/smart-contracts) but the `make install` step fails with the following error and no binaries being generated:
> 
> ```
> ➜  core git:(master) make install
> go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=kujira -X github.com/cosmos/cosmos-sdk/version.ServerName=kujirad -X github.com/cosmos/cosmos-sdk/version.Version=0.9.1-1-g5549501 -X github.com/cosmos/cosmos-sdk/version.Commit=554950147825e94fa52c3ff0a3b138568cf7c774 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/kujirad
> # github.com/Team-Kujira/core/cmd/kujirad
> ld: warning: '/private/var/folders/nh/78bdkps97rv6pdws74j1xy0w0000gn/T/go-link-1563688512/go.o' has malformed LC_DYSYMTAB, expected 133 undefined symbols to start at index 108006, found 251 undefined symbols starting at index 135
> ```
> 
> macOS: 14.2.1 go version: go1.20.6 darwin/arm64
> 
> Based on [#61229](https://github.com/golang/go/issues/61229) I suspect it has to do something with the apple linker. Any suggestion appreciated.

This looks Xcode related https://github.com/golang/go/issues/61558
